### ISSUE TITLE
[question] What is the chrome docker for?

### ISSUE THREAD

**Issue by Panderine** [lprat/docker-bastion#4]
Sorry if this is a dumb  question, but why is the chrome docker provided ? As far as I understand, chrome needs to be in the remote machine used as client to access guacamole in the bastion server right?

local chrome -> (HTML5) -> guacd-> (ssh) -> sshd server

**Comment by lprat** [comment]
Hi @Panderine ,

Sorry for my late answer.

Chrome docker should be used on the web admin interface (hypervisor, firewall, ...) because guacamole doesnt give the gateway to this protocol.
However, chrome docker can give vulnerabilities, you should prefer to use reverse proxy (ex: authelia) to have a "bastion" on the web admin interface.
